post http://localhost:3014/register
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

post http://localhost:3014/login
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###
get  http://localhost:3014/user/following
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3Mzk4ODU1fQ.Z0EeggFOp-8VAQ6z1n3yOnw9kWID4LqONuoidd_85QY
###
get  http://localhost:3014/user/followers
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3Mzk4ODU1fQ.Z0EeggFOp-8VAQ6z1n3yOnw9kWID4LqONuoidd_85QY

###
get http://localhost:3014/tweets/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3Mzk4ODU1fQ.Z0EeggFOp-8VAQ6z1n3yOnw9kWID4LqONuoidd_85QY

###
get http://localhost:3014/user/tweets/feed
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3MzM5MDM5fQ.xwqCKVvl3xSBeQ6sHHHdHb6VIoQqncu-5aPYE0EbYCA

###
get  http://localhost:3014/tweets/2/likes/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3MzM5MDM5fQ.xwqCKVvl3xSBeQ6sHHHdHb6VIoQqncu-5aPYE0EbYCA

###
get  http://localhost:3014/tweets/2/replies/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3MzM5MDM5fQ.xwqCKVvl3xSBeQ6sHHHdHb6VIoQqncu-5aPYE0EbYCA

###

get  http://localhost:3014/user/tweets/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3MzM5MDM5fQ.xwqCKVvl3xSBeQ6sHHHdHb6VIoQqncu-5aPYE0EbYCA

###
post http://localhost:3014/user/tweets/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3MzM5MDM5fQ.xwqCKVvl3xSBeQ6sHHHdHb6VIoQqncu-5aPYE0EbYCA
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

###
DELETE http://localhost:3014/tweets/10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3MzM5MDM5fQ.xwqCKVvl3xSBeQ6sHHHdHb6VIoQqncu-5aPYE0EbYCA
