post http://localhost:3000/login
Content-Type: application/json

{
  "id": 1,
  "name":"Ram"
}

###
get http://localhost:3000/faculty/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFtIiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2Nzc5OTM5ODZ9.PSQspZh9wPyBa6_qrSWTXhP373fSZYgqEKFX3rbOjxU
###
get http://localhost:3000/course/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFtIiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2Nzc5OTM5ODZ9.PSQspZh9wPyBa6_qrSWTXhP373fSZYgqEKFX3rbOjxU

###
post http://localhost:3000/login
Content-Type: application/json

{
  "id": 4,
  "name":"Lasya"
}
###
post http://localhost:3000/admin/slot
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGFzeWEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Nzc5OTYxOTd9.sJm5Vbq_4_e3XPNiieK9QKcGan4qcOETKam64xd2Wvs
Content-Type: application/json

{
  "id": "A3",
  "timings": [
    {
      "day": "mon",
      "start": "2023-03-03T15:15:22Z",
      "end": "2019-08-24T16:00:22Z"
    }
  ]
}

###
get http://localhost:3000/timetable
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFtIiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2NzgwMDg1MDN9.l-eBeOBsIpp-9Y0VxNRF3vjvOBcTHG1X8U-_YULCWo0

###
post http://localhost:3000/admin/faculty
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGFzeWEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Nzc5OTYxOTd9.sJm5Vbq_4_e3XPNiieK9QKcGan4qcOETKam64xd2Wvs
Content-Type: application/json

{
  "id": "6",
  "name": "Udit"
}

###
post http://localhost:3000/admin/student
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGFzeWEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Nzc5OTYxOTd9.sJm5Vbq_4_e3XPNiieK9QKcGan4qcOETKam64xd2Wvs
Content-Type: application/json

{
  "id": "6",
  "name": "Jyothsna"
}

###

post http://localhost:3000/admin/course
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGFzeWEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Nzc5OTYxOTd9.sJm5Vbq_4_e3XPNiieK9QKcGan4qcOETKam64xd2Wvs
Content-Type: application/json

{
  "id": "6",
  "name": "Lean Start-up Management",
  "slot_ids": [
    "A2","C2","E2"
  ],
  "faculty_ids": [
    4,5,6
  ],
  "course_type": "THEORY"
}

###
post http://localhost:3000/register
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFtIiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2Nzc5OTM5ODZ9.PSQspZh9wPyBa6_qrSWTXhP373fSZYgqEKFX3rbOjxU
Content-Type: application/json

{
  "course_id": "2",
  "faculty_id": "6",
  "slot_ids":  "A2"
}
